name: ai_cc
dependencies:
  - python=3.9
  - pip
  - pip:
    - pyyaml
    - pandas==1.2.4
    - numpy==1.20.3
    - scikit-learn==0.24.2
    - matplotlib==3.4.2
    - spacy==3.0.6
    - requests==2.31.0
    - nltk==3.8.1
    - requests-ratelimiter
    - SQLAlchemy==2.0.9
    - psycopg2-binary
    - python-dotenv==1.0.0
    - joblib
    - sentence-transformers
    - umap
    - scipy
    - bertopic
    - sentence-transformers