name: ai_cc
dependencies:
  - python=3.9
  - pip
  - pip:
    - pyyaml
    - pandas==1.2.4
    - numpy==1.20.3
    - spacy==3.0.6
    - requests==2.31.0
    - requests-ratelimiter
    - SQLAlchemy==2.0.9
    - psycopg2-binary
    - python-dotenv==1.0.0
    - joblib