# climate change

#- '("artificial intelligence" OR "artificial" OR "ai") AND "climate change"'
#- '("machine learning" OR "ml") AND "climate change"'
- '"deep learning" AND "climate change"'

# global warming

#- '("artificial intelligence" OR "artificial" OR "ai") AND "global warming"'
#- '("machine learning" OR "ml") AND "global warming"'
#- '"deep learning" AND "global warming"'

# climate crisis

#- '("artificial intelligence" OR "artificial" OR "ai") AND "climate crisis"'
#- '("machine learning" OR "ml") AND "climate crisis"'
#- '"deep learning" AND "climate crisis"'